### ISSUE TITLE
Finalise new group_by framework

### ISSUE THREAD

**Issue by xiaodaigh** [xiaodaigh/disk.frame#225]
- [x] Update all README and vignette
- [x] Write a blog on how to define custom group_by
- [x] Write tests
- [x] summarise without group_by
- [x] nested group by warning; see #226
- [x] 1±sum(col1); see #226
- [x] list(unique(col1)) ; see #226
